package io.github.baijifeilong.chat.tool;

import com.google.common.base.CaseFormat;
import com.zaxxer.hikari.HikariDataSource;
import io.github.baijifeilong.chat.App;
import lombok.SneakyThrows;
import lombok.experimental.FieldNameConstants;
import lombok.extern.slf4j.Slf4j;
import org.jooq.codegen.DefaultGeneratorStrategy;
import org.jooq.codegen.GenerationTool;
import org.jooq.codegen.JavaGenerator;
import org.jooq.codegen.JavaWriter;
import org.jooq.meta.Definition;
import org.jooq.meta.TableDefinition;
import org.jooq.meta.TypedElementDefinition;
import org.jooq.meta.jaxb.*;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by BaiJiFeiLong@gmail.com at 2018/12/25 下午2:15
 * <p>
 * JOOQ模型生成器
 */
public class MyJooqGenerator implements MyEnvironment {
    private static final String[] TABLE_PREFIXES = new String[]{"wb"};

    private static void initDatabase() {
        JdbcTemplate jdbcTemplate = new JdbcTemplate(new HikariDataSource() {{
            setJdbcUrl(JDBC_URL);
            setUsername(JDBC_USERNAME);
            setPassword(JDBC_PASSWORD);
        }});
        jdbcTemplate.execute("DROP SCHEMA IF EXISTS thatcher");
        jdbcTemplate.execute("CREATE SCHEMA thatcher");
        jdbcTemplate.execute("USE thatcher");
        jdbcTemplate.execute("CREATE TABLE great_user(ID INT PRIMARY KEY AUTO_INCREMENT, username TEXT)");
    }

    @SneakyThrows
    public static void main(String[] args) {
        initDatabase();
        GenerationTool.generate(new Configuration()
                .withJdbc(new Jdbc()
                        .withUrl(JDBC_URL)
                        .withUser(JDBC_USERNAME)
                        .withPassword(JDBC_PASSWORD))
                .withGenerator(new Generator()
                        .withName(MyJavaGenerator.class.getName())
                        .withDatabase(new Database()
                                .withSchemata(
                                        new Schema().withInputSchema("thatcher"),
                                        new Schema().withInputSchema("chat"))
                                .withExcludes(".*\\d+"))
                        .withStrategy(new Strategy()
                                .withName(MyStrategy.class.getName()))
                        .withGenerate(new Generate()
                                .withJavaTimeTypes(true))
                        .withTarget(new Target()
                                .withPackageName(App.class.getPackage().getName() + ".generated.jooq")
                                .withDirectory("src/main/java"))));

    }

    @Slf4j
    public static class MyStrategy extends DefaultGeneratorStrategy {
        private Pattern pattern = Pattern.compile(String.format("(%s)_(.+)", String.join("|", MyJooqGenerator.TABLE_PREFIXES)));

        @Override
        public String getJavaClassName(Definition definition, Mode mode) {
            String name = super.getJavaClassName(definition, mode);
            String snakeCaseName = CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, name);
            Matcher matcher = pattern.matcher(snakeCaseName);
            if (!matcher.matches()) {
                return name;
            }
            String newSnakeCaseName = matcher.group(2);
            String newName = CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, newSnakeCaseName);
            log.info("{} => {}", name, newName);
            return newName;
        }
    }

    public static class MyJavaGenerator extends JavaGenerator {
        @Override
        protected void generateRecordGetter(TypedElementDefinition<?> column, int index, JavaWriter out) {
            super.generateRecordGetter(column, index, out);
            String camelCase = CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, column.getName());
            out.print("\n    /**\n     * Generated by baijifeilong@gmail.com\n     */\n    private %s %s;\n",
                    out.ref(getJavaType(column.getType())), camelCase);
        }

        @Override
        protected void generateRecordClassJavadoc(TableDefinition table, JavaWriter out) {
            super.generateRecordClassJavadoc(table, out);
            out.println("@" + FieldNameConstants.class.getName());
        }
    }
}
